import std/[os, osproc, streams, strformat, strutils]
import jsony
from ./git_ops import ensureScriptoriumIgnored
from ./config import defaultConfig

const
  PlanBranch = "scriptorium/plan"
  SpecPlaceholder = "# Spec\n\nThis file will be generated by `scriptorium plan` using the Architect.\nThe Architect reads your AGENTS.md to understand the project before building the spec.\n"
  AgentsFileName = "AGENTS.md"
  AgentsTemplate = staticRead("prompts/agents_example.md")
  MakefileName = "Makefile"
  MakefileTemplate = ".PHONY: test build\n\ntest:\n\t@echo \"no tests configured\"\n\nbuild:\n\t@echo \"no build configured\"\n"
  ConfigFileName = "scriptorium.json"
  PlanDirs = [
    "areas",
    "tickets/open",
    "tickets/in-progress",
    "tickets/done",
    "tickets/stuck",
    "decisions",
  ]

proc gitRun(dir: string, args: varargs[string]) =
  ## Run a git subcommand in dir, raising IOError on non-zero exit.
  let argsSeq = @args
  let allArgs = @["-C", dir] & argsSeq
  let p = startProcess("git", args = allArgs, options = {poUsePath, poStdErrToStdOut})
  let output = p.outputStream.readAll()
  let rc = p.waitForExit()
  p.close()
  if rc != 0:
    let argsStr = argsSeq.join(" ")
    raise newException(IOError, fmt"git {argsStr} failed: {output.strip()}")

proc gitCheck(dir: string, args: varargs[string]): int =
  ## Run a git subcommand in dir, returning exit code and discarding output.
  let allArgs = @["-C", dir] & @args
  let p = startProcess("git", args = allArgs, options = {poUsePath, poStdErrToStdOut})
  discard p.outputStream.readAll()
  result = p.waitForExit()
  p.close()

proc resolveDefaultBranch(repoPath: string): string =
  ## Dynamically detect the default branch for the repository.
  ## Checks refs/remotes/origin/HEAD first, then probes for master, main, develop.
  let symrefProcess = startProcess(
    "git",
    args = @["-C", repoPath, "symbolic-ref", "refs/remotes/origin/HEAD"],
    options = {poUsePath, poStdErrToStdOut},
  )
  let symrefOutput = symrefProcess.outputStream.readAll()
  let symrefRc = symrefProcess.waitForExit()
  symrefProcess.close()
  if symrefRc == 0:
    let symref = symrefOutput.strip()
    let prefix = "refs/remotes/origin/"
    if symref.startsWith(prefix):
      result = symref[prefix.len..^1]
      return

  const ProbeBranches = ["master", "main", "develop"]
  for branch in ProbeBranches:
    if gitCheck(repoPath, "rev-parse", "--verify", branch) == 0:
      result = branch
      return

  raise newException(IOError, "cannot determine default branch: refs/remotes/origin/HEAD is not set and none of master, main, develop exist")

proc runInit*(path: string, quiet: bool = false) =
  ## Initialize a new scriptorium workspace in the given git repository.
  let target = if path.len > 0: absolutePath(path) else: getCurrentDir()

  if gitCheck(target, "rev-parse", "--git-dir") != 0:
    raise newException(ValueError, fmt"{target} is not a git repository")

  if gitCheck(target, "rev-parse", "--verify", PlanBranch) == 0:
    raise newException(ValueError, "workspace already initialized (scriptorium/plan branch exists)")

  let defaultBranch = resolveDefaultBranch(target)
  discard execCmdEx("git -C " & quoteShell(target) & " remote set-head origin " & quoteShell(defaultBranch))

  ensureScriptoriumIgnored(target)

  let agentsPath = target / AgentsFileName
  let createdAgents = not fileExists(agentsPath)
  if createdAgents:
    writeFile(agentsPath, AgentsTemplate)
    gitRun(target, "add", AgentsFileName)
    gitRun(target, "commit", "-m", "scriptorium: add AGENTS.md from template")

  let makefilePath = target / MakefileName
  let createdMakefile = not fileExists(makefilePath)
  if createdMakefile:
    writeFile(makefilePath, MakefileTemplate)
    gitRun(target, "add", MakefileName)
    gitRun(target, "commit", "-m", "scriptorium: add starter Makefile")

  let configPath = target / ConfigFileName
  let createdConfig = not fileExists(configPath)
  if createdConfig:
    let configJson = defaultConfig().toJson()
    writeFile(configPath, configJson & "\n")

  let tmpPlan = target / ".scriptorium" / "plan_init"
  if dirExists(tmpPlan):
    removeDir(tmpPlan)

  gitRun(target, "worktree", "add", "--orphan", "-b", PlanBranch, tmpPlan)
  defer:
    discard execCmdEx(
      "git -C " & quoteShell(target) & " worktree remove --force " & quoteShell(tmpPlan)
    )

  for d in PlanDirs:
    createDir(tmpPlan / d)
    writeFile(tmpPlan / d / ".gitkeep", "")
  writeFile(tmpPlan / "spec.md", SpecPlaceholder)

  gitRun(tmpPlan, "add", ".")
  gitRun(tmpPlan, "commit", "-m", "scriptorium: initialize plan branch")

  if not quiet:
    echo "Initialized scriptorium workspace."
    echo ""
    echo "Created:"
    echo &"  Branch: {PlanBranch}"
    let dirsStr = PlanDirs.join(", ")
    echo &"    Directories: {dirsStr}"
    echo "    spec.md"
    if createdAgents:
      echo &"  {AgentsFileName}"
    if createdMakefile:
      echo &"  {MakefileName}"
    if createdConfig:
      echo &"  {ConfigFileName}"
    echo ""
    echo "Next steps:"
    if createdAgents:
      echo &"  Edit {AgentsFileName} to describe your project."
    if createdConfig:
      echo &"  Edit {ConfigFileName} to configure models and harness."
    if createdMakefile:
      echo &"  Edit {MakefileName} to set up real test/build targets."
    echo "  Run `scriptorium plan` to build your spec."
    echo "  Run `scriptorium run` to start the orchestrator."
